/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Nekhross
 */
public class pnel_registroUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form pnel_inicioSesion
     */
    public pnel_registroUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelinicioSesion = new javax.swing.JPanel();
        panelRound1 = new Clases.PanelRound();
        btnregistrar = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        lblclave = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblnombres = new javax.swing.JLabel();
        lblapellidos = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        panelRound2 = new Clases.PanelRound();
        btncancelar = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        lblcedula = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        lblUsuario1 = new javax.swing.JLabel();
        btnmostrar = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();

        panelinicioSesion.setBackground(new java.awt.Color(4, 50, 99));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        btnregistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnregistrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(0, 68, 129));
        btnregistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnregistrar.setText("Registrar Usuario");
        btnregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnregistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnregistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        txtusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblclave.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblclave.setForeground(new java.awt.Color(255, 255, 255));
        lblclave.setText("Contraseña: (*)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registro de Cuenta");

        lblnombres.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblnombres.setForeground(new java.awt.Color(255, 255, 255));
        lblnombres.setText("Nombres: (*)");

        lblapellidos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblapellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblapellidos.setText("Apellidos: (*)");

        txtapellidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtapellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);

        btncancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 51, 0));
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar.setText("Cancelar");
        btncancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btncancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        txtnombres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblcedula.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblcedula.setForeground(new java.awt.Color(255, 255, 255));
        lblcedula.setText("Cedula: (*)");

        txtcedula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario1.setText("Usuario: (*)");

        btnmostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnmostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/ojoCerrado.png"))); // NOI18N
        btnmostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtclave.setBorder(null);

        javax.swing.GroupLayout panelinicioSesionLayout = new javax.swing.GroupLayout(panelinicioSesion);
        panelinicioSesion.setLayout(panelinicioSesionLayout);
        panelinicioSesionLayout.setHorizontalGroup(
            panelinicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinicioSesionLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2))
            .addGroup(panelinicioSesionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblUsuario1))
            .addGroup(panelinicioSesionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblclave))
            .addGroup(panelinicioSesionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblapellidos))
            .addGroup(panelinicioSesionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblcedula))
            .addGroup(panelinicioSesionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelinicioSesionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelinicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombres)
                    .addGroup(panelinicioSesionLayout.createSequentialGroup()
                        .addGroup(panelinicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmostrar))))
        );
        panelinicioSesionLayout.setVerticalGroup(
            panelinicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinicioSesionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(lblUsuario1)
                .addGap(8, 8, 8)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblclave)
                .addGap(14, 14, 14)
                .addGroup(panelinicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnombres)
                .addGap(8, 8, 8)
                .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblapellidos)
                .addGap(8, 8, 8)
                .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblcedula)
                .addGap(8, 8, 8)
                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(panelinicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelinicioSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelinicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btncancelar;
    public javax.swing.JLabel btnmostrar;
    public javax.swing.JLabel btnregistrar;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel lblUsuario1;
    public javax.swing.JLabel lblapellidos;
    public javax.swing.JLabel lblcedula;
    public javax.swing.JLabel lblclave;
    public javax.swing.JLabel lblnombres;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound2;
    public javax.swing.JPanel panelinicioSesion;
    public javax.swing.JTextField txtapellidos;
    public javax.swing.JTextField txtcedula;
    public javax.swing.JPasswordField txtclave;
    public javax.swing.JTextField txtnombres;
    public javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
