/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Nekhross
 */
public class pnel_Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form pnel_Dashboard
     */
    public pnel_Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbienvenida = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblindicadorVentana5 = new javax.swing.JLabel();
        lblconteoalumnos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        lblindicadorVentana11 = new javax.swing.JLabel();
        lblindicadorVentana12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        lblindicadorVentana13 = new javax.swing.JLabel();
        lblconteousuarios = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblbienvenida.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblbienvenida.setForeground(new java.awt.Color(4, 50, 99));
        lblbienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbienvenida.setText("BIENVENIDO AL SISTEMA, NOMBRE");

        jPanel16.setBackground(new java.awt.Color(0, 204, 153));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblindicadorVentana5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblindicadorVentana5.setForeground(new java.awt.Color(255, 255, 255));
        lblindicadorVentana5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblindicadorVentana5.setText("Alumnos Registrados");
        lblindicadorVentana5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel16.add(lblindicadorVentana5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        lblconteoalumnos.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblconteoalumnos.setForeground(new java.awt.Color(255, 255, 255));
        lblconteoalumnos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblconteoalumnos.setText("0");
        jPanel16.add(lblconteoalumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 47));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/alumnoico.png"))); // NOI18N
        jPanel16.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 110, 160));

        jPanel17.setBackground(new java.awt.Color(0, 153, 153));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblindicadorVentana11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblindicadorVentana11.setForeground(new java.awt.Color(255, 255, 255));
        lblindicadorVentana11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblindicadorVentana11.setText("Oficios Registrados");
        lblindicadorVentana11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel17.add(lblindicadorVentana11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        lblindicadorVentana12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblindicadorVentana12.setForeground(new java.awt.Color(255, 255, 255));
        lblindicadorVentana12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblindicadorVentana12.setText("0");
        jPanel17.add(lblindicadorVentana12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 47));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconodocu.png"))); // NOI18N
        jPanel17.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 120, -1));

        jPanel18.setBackground(new java.awt.Color(0, 102, 153));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblindicadorVentana13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblindicadorVentana13.setForeground(new java.awt.Color(255, 255, 255));
        lblindicadorVentana13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblindicadorVentana13.setText("Cuentas Registradas");
        lblindicadorVentana13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel18.add(lblindicadorVentana13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        lblconteousuarios.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblconteousuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblconteousuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblconteousuarios.setText("0");
        jPanel18.add(lblconteousuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 47));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/usuariodash.png"))); // NOI18N
        jPanel18.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 120, 100));

        jPanel1.setBackground(new java.awt.Color(108, 117, 125));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Administracion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblbienvenida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblbienvenida)
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(325, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    public javax.swing.JLabel lblbienvenida;
    public javax.swing.JLabel lblconteoalumnos;
    public javax.swing.JLabel lblconteousuarios;
    private javax.swing.JLabel lblindicadorVentana11;
    private javax.swing.JLabel lblindicadorVentana12;
    private javax.swing.JLabel lblindicadorVentana13;
    private javax.swing.JLabel lblindicadorVentana5;
    // End of variables declaration//GEN-END:variables
}
