/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Nekhross
 */
public class pnel_inicioSesion extends javax.swing.JPanel {

    /**
     * Creates new form pnel_inicioSesion
     */
    public pnel_inicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelinicioSesion = new javax.swing.JPanel();
        txtusuario = new javax.swing.JTextField();
        txtclave = new javax.swing.JPasswordField();
        lblclave = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnmostrar = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnmostrar1 = new javax.swing.JLabel();
        btnmostrar2 = new javax.swing.JLabel();
        panelRound1 = new Clases.PanelRound();
        btniniciarSesion = new javax.swing.JLabel();
        panelRound2 = new Clases.PanelRound();
        btnregistrarse = new javax.swing.JLabel();

        panelinicioSesion.setBackground(new java.awt.Color(0, 51, 51));
        panelinicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusuario.setBackground(new java.awt.Color(0, 51, 51));
        txtusuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setBorder(null);
        txtusuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtusuario.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtusuario.setFocusable(false);
        panelinicioSesion.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 270, 361, 36));

        txtclave.setBackground(new java.awt.Color(0, 51, 51));
        txtclave.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtclave.setForeground(new java.awt.Color(255, 255, 255));
        txtclave.setBorder(null);
        txtclave.setCaretColor(new java.awt.Color(255, 255, 255));
        txtclave.setFocusable(false);
        panelinicioSesion.add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 361, 36));

        lblclave.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblclave.setForeground(new java.awt.Color(255, 255, 255));
        lblclave.setText("Contraseña:");
        panelinicioSesion.add(lblclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Acceso al sistema");
        panelinicioSesion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        btnmostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnmostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/ojoCerrado.png"))); // NOI18N
        btnmostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelinicioSesion.add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, 36));

        lblusuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(255, 255, 255));
        lblusuario.setText("Usuario:");
        panelinicioSesion.add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 220, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/chofer (2).png"))); // NOI18N
        panelinicioSesion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panelinicioSesion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 306, 361, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        panelinicioSesion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 361, -1));

        btnmostrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnmostrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconousuario.png"))); // NOI18N
        btnmostrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelinicioSesion.add(btnmostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 270, -1, -1));

        btnmostrar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnmostrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/contraseña.png"))); // NOI18N
        btnmostrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelinicioSesion.add(btnmostrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        btniniciarSesion.setBackground(new java.awt.Color(0, 51, 51));
        btniniciarSesion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btniniciarSesion.setForeground(new java.awt.Color(0, 51, 51));
        btniniciarSesion.setText("   Iniciar Sesion");
        btniniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btniniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btniniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelinicioSesion.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 150, 30));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        btnregistrarse.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnregistrarse.setForeground(new java.awt.Color(0, 51, 255));
        btnregistrarse.setText("     Registrarse");
        btnregistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnregistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnregistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelinicioSesion.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelinicioSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelinicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btniniciarSesion;
    public javax.swing.JLabel btnmostrar;
    public javax.swing.JLabel btnmostrar1;
    public javax.swing.JLabel btnmostrar2;
    public javax.swing.JLabel btnregistrarse;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel lblclave;
    public javax.swing.JLabel lblusuario;
    private Clases.PanelRound panelRound1;
    private Clases.PanelRound panelRound2;
    public javax.swing.JPanel panelinicioSesion;
    public javax.swing.JPasswordField txtclave;
    public javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
