/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Nekhross
 */
public class pnel_Cuentas extends javax.swing.JPanel {

    /**
     * Creates new form pnel_Cuentas
     */
    public pnel_Cuentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblusuario2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        lblclave = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        lblnombres = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        lblapellidos = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        lblcedula = new javax.swing.JLabel();
        lblnumeroid = new javax.swing.JLabel();
        lblid1 = new javax.swing.JLabel();
        panelRound6 = new Clases.PanelRound();
        btnmodificarUsuario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 50, 99));
        jLabel1.setText("Mi Perfil");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/usuario2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 360, 40));

        jPanel2.setBackground(new java.awt.Color(0, 140, 135));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Informacion General");

        lblusuario2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblusuario2.setForeground(new java.awt.Color(255, 255, 255));
        lblusuario2.setText("Usuario: (*)");

        txtusuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblclave.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblclave.setForeground(new java.awt.Color(255, 255, 255));
        lblclave.setText("Contraseña: (*)");

        txtclave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblnombres.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblnombres.setForeground(new java.awt.Color(255, 255, 255));
        lblnombres.setText("Nombres: (*)");

        txtnombres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblapellidos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblapellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblapellidos.setText("Apellidos: (*)");

        txtapellidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtcedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblcedula.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblcedula.setForeground(new java.awt.Color(255, 255, 255));
        lblcedula.setText("Cedula: (*)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblcedula)
                    .addComponent(lblapellidos)
                    .addComponent(lblnombres)
                    .addComponent(lblclave)
                    .addComponent(lblusuario2)
                    .addComponent(jLabel2)
                    .addComponent(txtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(txtclave)
                    .addComponent(txtnombres)
                    .addComponent(txtapellidos)
                    .addComponent(txtcedula))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblusuario2)
                .addGap(18, 18, 18)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblclave)
                .addGap(18, 18, 18)
                .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblnombres)
                .addGap(18, 18, 18)
                .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblapellidos)
                .addGap(18, 18, 18)
                .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblcedula)
                .addGap(18, 18, 18)
                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lblnumeroid.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblnumeroid.setForeground(new java.awt.Color(4, 50, 99));
        lblnumeroid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnumeroid.setText("0");

        lblid1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblid1.setForeground(new java.awt.Color(4, 50, 99));
        lblid1.setText("Numero de cuenta:");

        panelRound6.setBackground(new java.awt.Color(0, 140, 135));
        panelRound6.setRoundBottomLeft(50);
        panelRound6.setRoundBottomRight(50);
        panelRound6.setRoundTopLeft(50);
        panelRound6.setRoundTopRight(50);

        btnmodificarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnmodificarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnmodificarUsuario.setText("GUARDAR");
        btnmodificarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmodificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmodificarUsuario)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblid1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblnumeroid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblid1)
                    .addComponent(lblnumeroid))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnmodificarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblUsuario;
    public javax.swing.JLabel lblapellidos;
    public javax.swing.JLabel lblcedula;
    public javax.swing.JLabel lblclave;
    public javax.swing.JLabel lblid1;
    public javax.swing.JLabel lblnombres;
    public javax.swing.JLabel lblnumeroid;
    public javax.swing.JLabel lblusuario2;
    private Clases.PanelRound panelRound6;
    public javax.swing.JTextField txtapellidos;
    public javax.swing.JTextField txtcedula;
    public javax.swing.JTextField txtclave;
    public javax.swing.JTextField txtnombres;
    public javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
